CREATE TABLE IF NOT EXISTS nutrity_users (
    id VARCHAR(24) PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE,
    name VARCHAR(160) NOT NULL,
    photo_url VARCHAR(600),
    birth_date DATE,
    gender VARCHAR(32),
    daily_calorie_goal INTEGER NOT NULL,
    locale VARCHAR(12) NOT NULL,
    premium BOOLEAN NOT NULL DEFAULT FALSE,
    premium_expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS nutrity_meals (
    id VARCHAR(80) PRIMARY KEY,
    user_id VARCHAR(24) NOT NULL REFERENCES nutrity_users(id),
    descricao VARCHAR(1000) NOT NULL,
    descricao_original VARCHAR(1000),
    calorias INTEGER NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    origem VARCHAR(24) NOT NULL,
    ai_confidence DOUBLE PRECISION,
    nota VARCHAR(2000),
    icon_key VARCHAR(40) NOT NULL,
    protein_grams INTEGER NOT NULL,
    carbohydrate_grams INTEGER NOT NULL,
    fat_grams INTEGER NOT NULL,
    modified_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_meals_user ON nutrity_meals(user_id);

CREATE TABLE IF NOT EXISTS nutrition_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(24) NOT NULL REFERENCES nutrity_users(id),
    entity_id VARCHAR(80) NOT NULL,
    modified_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    payload_json TEXT,
    CONSTRAINT uk_goal_user_entity UNIQUE(user_id, entity_id)
);

CREATE TABLE IF NOT EXISTS sync_changes (
    sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(24) NOT NULL REFERENCES nutrity_users(id),
    entity_type VARCHAR(24) NOT NULL,
    entity_id VARCHAR(80) NOT NULL,
    operation VARCHAR(12) NOT NULL,
    modified_at TIMESTAMP WITH TIME ZONE NOT NULL,
    payload_json TEXT,
    operation_id VARCHAR(36) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sync_changes_user_sequence ON sync_changes(user_id, sequence);
CREATE INDEX IF NOT EXISTS idx_sync_changes_identity ON sync_changes(user_id, entity_type, entity_id, sequence);

CREATE TABLE IF NOT EXISTS processed_sync_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(24) NOT NULL REFERENCES nutrity_users(id),
    operation_id VARCHAR(36) NOT NULL,
    request_digest VARCHAR(64) NOT NULL,
    result_status VARCHAR(16) NOT NULL,
    change_sequence BIGINT NOT NULL REFERENCES sync_changes(sequence),
    processed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_processed_user_operation UNIQUE(user_id, operation_id)
);
